version: '2'

services:
    auv-rev-proxy:
        depends_on:
            - auv-wiki
        image: auv-rev-proxy
        ports: 
            - 80:8080

    auv-wiki:
        image: auv-wiki
        ports:
            - 3000:3000
